spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: "{cipher}AYC3wpasL3yKAVDrba9mlGmvFdFNY3mMmt4ph9+mSO8Sci96scQjlcierz2l6HjdDt7BolGyqA+QUOrkqQHKsC3nG91+OMSh55/M97hYSxfl+JvIt153vefD243Q10+9SHWBsaazYIRQBXUhiUKfpcxwSfgE2R5yKKQRTKSIKUprsxWAzX0u1s+lW5eym4i4H0wxNX8JZQ9WPxTt44pFYnrAj9mMeh4bzUjbKIDNxSGzYAS5J+2xUCt0nPM65qHsEZ5kXQM1jlYMFQ+wpLwNfsjFQTgXcWb/wewXBuYBhoipeYxXPJVjSNTCON4HabQBSNk5sG4OqYxqI9hdhPhkze55ZdgNHTcqOTcfght6glMyV4+ZLdTQbXo59XSB2eiGdNi8BqxT2TArlUSX0hOdG2XhSbVAUvY2a3N4p00Sf7JZs3wu6ayVemNVq7BO+i6eCSC/9Oxsimr8ij1YjnXeCxjd6WLdbNpb1MR5lInfe0JYhqq7B8BOFWmXz7/pPy2qQw29yVIhfgU4TlM8/QZvsoPsBEApt42FNmbvy7FDM87P7g=="

token:
  expiration_time: 86400000
  secret: "{cipher}AYBbRbZf+pBLV5kFkUeWu4TefP4CUMTzzAPqjH/X1Vo/TB/neO7n9OrnS8T6AMKx/gh7NeoIiCkzzUaLDq+f+R+YFvfnM4RCSHm5UfEOREUE33zKm3CJCoUJmdzCVHsq0iv8JYHBdbQaY8m65au4WFB8iZNZgrA+nNPFsu1rnkwXyB2ECCcRlydejplcGPf5nhq7ksDKCrts0bQICGAC84ZN8nWih/+MNytNYWgZinwLFQVwG5ctfoYqrrb4JvG9FyrcxIu1U6aW9zo0Neoqa29mW8g9zf+Q78W3V2aDPSScm0vshQ2nDvbT+pgFZqbYlwKFzCTDUcApjHeJUqXsXvyYaUQt1jVCK/5cQPhD+4NaHkCja0ajry4l5OayJa8jh/yrYcNg7j0tRiz1xqXiyvrYjYp33MG3ap6GBCGhSdRM1px3Kx/wGq7eOr0Mr3O3vxCG3ys42eDmKSzxwORqvnuFg12DrZl7Z+4lvRkDHs75v8FnpA7uSZFY3PUSf8AbTQKixgeDOcYivzy0EW3Wh5vINjGqaPlASdGeJgWgcKEl+sJ/M6IgfptlseavAIByXYQHCPunnYGHvn2Lulifqel0R/s4/iMlVak7gvuCR5Ym/C/AlIaK46i2MfUkYsFHuyo="

gateway:
  ip: 172.19.0.1
# mac : 192.168.103.67 / pc : 192.168.55.187

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item.
